// <auto-generated />
namespace Proje4_EntityFrameworkCodeFirstMovie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig2));
        
        string IMigrationMetadata.Id
        {
            get { return "202507170827044_mig2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
